<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Async Await</title>
  </head>
  <body>
    <script>
      function handleError(err) {
        console.error("Oh no!");
        console.error(err);
      }
      function breathe(amount) {
        return new Promise((resolve, reject) => {
          if (amount < 500) {
            reject("THat is too small of a value");
          }
          setTimeout(() => resolve(`Done for ${amount} ms`), amount);
        });
      }
      function catchError(fn) {
        return function (...args) {
          return fn(...args).catch(handleError);
        };
      }
      async function go(name, msg) {
        // try {
        //   const response1 = await breathe(1000);
        //   console.log(response1);
        //   const response2 = await breathe(800);
        //   console.log(response2);
        //   const response3 = await breathe(700);
        //   console.log(response3);
        //   const response4 = await breathe(400);
        //   console.log(response4);
        // } catch (err) {
        //   console.error(err);
        //   console.error("you screwed up");
        // }
        console.log(`Starting for ${name} with ${msg}`);
        const response1 = await breathe(1000);
        console.log(response1);
        const response2 = await breathe(800);
        console.log(response2);
        const response3 = await breathe(700);
        console.log(response3);
        const response4 = await breathe(400);
        console.log(response4);
      }
      const wrappedFunction = catchError(go);
      wrappedFunction("Cricadev", "I love you");

      // catching errors is situational
    </script>
  </body>
</html>
